version: '3.9'

services:
  backend:
    container_name: api
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DATABASE_PORT}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASS}
      DB_NAME: ${DATABASE}
      SALT: ${SALT}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      DATABASE: ${DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_HOST: db
      DATABASE_USER: ${DATABASE_USER}
    links:
      - db:database
    volumes:
      - './:/src'
  # Requires gest-frontend in a parallel directory
  # if you have not already run from this directory:
  # cd .. && git clone https://github.com/Maximumz/gest-frontend
  frontend:
    container_name: frontend
    build: ../gest-frontend/
    depends_on:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - './:/src'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local
  pgadmin-data: