# fly.toml file generated for gestdb on 2022-12-12T09:00:15+13:00

app = "gestdb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

  [[services.ports]]
    handlers = ["pg_tls"]
    port = 5432
